apiVersion: polyaxon.com/v1
kind: Cluster
metadata:
  name: dask-cluster-simple
  namespace: polyaxon-agent
  labels:
    app.kubernetes.io/name: dask-cluster-simple
    app.kubernetes.io/instance: dask-cluster-simple
daskClusterSpec:
  service:
    type: ClusterIP
    ports:
    - name: tcp-comm
      protocol: TCP
      port: 8786
      targetPort: "tcp-comm"
    - name: http-dashboard
      protocol: TCP
      port: 8787
      targetPort: "http-dashboard"

  replicaSpecs:
    Worker:
      replicas: 1
      template:
        spec:
          containers:
          - name: worker
            image: "ghcr.io/dask/dask:latest"
            imagePullPolicy: "IfNotPresent"
            args:
              - dask-worker
              - --name
              - $(DASK_WORKER_NAME)
              - --dashboard
              - --dashboard-address
              - "8788"
            ports:
              - name: http-dashboard
                containerPort: 8788
                protocol: TCP

    Scheduler:
      replicas: 1
      template:
        spec:
          containers:
          - name: scheduler
            image: "ghcr.io/dask/dask:latest"
            imagePullPolicy: "IfNotPresent"
            args:
              - dask-scheduler
            ports:
              - name: tcp-comm
                containerPort: 8786
                protocol: TCP
              - name: http-dashboard
                containerPort: 8787
                protocol: TCP
            readinessProbe:
              httpGet:
                port: http-dashboard
                path: /health
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
              httpGet:
                port: http-dashboard
                path: /health
              initialDelaySeconds: 15
              periodSeconds: 20
